name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  origin-unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.14.15
      - name: install go tool
        run: |
          GO111MODULE=off go get -u github.com/myitcv/gobin
      - name: install system tool
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc haveged libtool make
      - name: unit-test
        run: |
          make unit-test

      #upload-codecov:
      #  uses: codecov/codecov-action@v3
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
  origin-integration-test:
    needs:
    - origin-unit-test
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.14.15
      - name: install go tool
        run: |
          GO111MODULE=off go get -u github.com/myitcv/gobin
      - name: install system tool
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc haveged libtool make
      - name: unit-test
        run: |
          make unit-test

  #go-qa-l0:
  #  uses: atomyze-foundation/workflows/.github/workflows/go-validate--v1.yml@main

  #go-qa-l2:
  #  needs:
  #    - go-qa-l1
  #  uses: atomyze-foundation/workflows/.github/workflows/go-test--v1.yml@main

  #go-qa-l3:
  #  needs:
  #    - go-qa-l2
  #  uses: atomyze-foundation/workflows/.github/workflows/go-static--v1.yml@main
