name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  go-qa-l0:
    uses: atomyze-foundation/workflows/.github/workflows/go-validate--v1.yml@main

  go-qa-l1:
    needs:
      - go-qa-l0
    uses: atomyze-foundation/workflows/.github/workflows/go-lint--v1.yml@main

  go-qa-l2:
    needs:
      - go-qa-l1
    uses: atomyze-foundation/workflows/.github/workflows/go-test--v1.yml@main

  go-qa-l3:
    needs:
      - go-qa-l2
    uses: atomyze-foundation/workflows/.github/workflows/go-static--v1.yml@main
